# Generated by Django 5.0.4 on 2024-04-25 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField()),
                ('model', models.CharField()),
                ('effective_range', models.FloatField()),
                ('cruising_speed', models.FloatField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('short_name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('continent', models.CharField()),
                ('currency', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField()),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('iata_short', models.CharField()),
                ('icao_short', models.CharField()),
                ('timezone', models.CharField()),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.country')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_timestamp', models.DateTimeField()),
                ('arrival_timestamp', models.DateTimeField()),
                ('aircraft_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.aircrafttype')),
                ('airline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.airline')),
                ('arrival_airport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_airport_id', to='scanner.airport')),
                ('departure_airport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_airport_id', to='scanner.airport')),
                ('tariff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.tariff')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlightReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.flight')),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.reservation')),
            ],
        ),
    ]
